<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Application\" />
      <Folder Include="Tests\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Logging\Logging.csproj" />
      <ProjectReference Include="..\Messaging\Messaging.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0-release-24352-06" />
      <PackageReference Include="Moq" Version="4.20.70" />
      <PackageReference Include="xunit" Version="2.9.0" />
    </ItemGroup>

</Project>
